// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Test: typeof import('./src/components/test/index.vue')['default']
    TestInner: typeof import('./src/components/test/testInner/index.vue')['default']
    TestTwo: typeof import('./src/components/test/testTwo/index.vue')['default']
  }
}

export { }
