// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppSvgIcon: typeof import('./components/appSvgIcon/index.vue')['default']
    ButtonLoading: typeof import('./components/buttonLoading/index.vue')['default']
    ChangeTheme: typeof import('./components/ChangeTheme/index.vue')['default']
    CreateElement: typeof import('./components/CreateElement/index.vue')['default']
    CustomButton: typeof import('./components/CustomButton/index.vue')['default']
    CustomCheckBox: typeof import('./components/customCheckBox/index.vue')['default']
    CustomDataPicker: typeof import('./components/customDataPicker/index.vue')['default']
    CustomDrawer: typeof import('./components/CustomDrawer/index.vue')['default']
    CustomEllipsisBox: typeof import('./components/CustomEllipsisBox/index.vue')['default']
    CustomForm: typeof import('./components/customForm/index.vue')['default']
    CustomInput: typeof import('./components/customInput/index.vue')['default']
    CustomProgress: typeof import('./components/CustomProgress/index.vue')['default']
    CustomRadio: typeof import('./components/customRadio/index.vue')['default']
    CustomSelect: typeof import('./components/customSelect/index.vue')['default']
    CustomSteps: typeof import('./components/CustomSteps/index.vue')['default']
    CustomTable: typeof import('./components/CustomTable/index.vue')['default']
    CustomUpload: typeof import('./components/CustomUpload/index.vue')['default']
    Dialog: typeof import('./components/dialog/index.vue')['default']
    Driver: typeof import('./components/Driver/index.vue')['default']
    Echarts: typeof import('./components/echarts/index.vue')['default']
    EllipsisBox: typeof import('./components/ellipsisBox/index.vue')['default']
    FormCustom: typeof import('./components/FormCustom/index.vue')['default']
    InquiryTitle: typeof import('./components/InquiryTitle/index.vue')['default']
    LogicFlow: typeof import('./components/logicFlow/index.vue')['default']
    LogicFlowToolBar: typeof import('./components/logicFlow/logicFlowToolBar/index.vue')['default']
    MainCard: typeof import('./components/mainCard/index.vue')['default']
    Map: typeof import('./components/map/index.vue')['default']
    More: typeof import('./components/CustomEllipsisBox/more.vue')['default']
    MoreContent: typeof import('./components/CustomEllipsisBox/moreContent.vue')['default']
    PopoverCustom: typeof import('./components/popoverCustom/index.vue')['default']
    ReSeamlessScroll: typeof import('./components/reSeamlessScroll/index.vue')['default']
    SearchForm: typeof import('./components/SearchForm/index.vue')['default']
    TabBar: typeof import('./components/tabBar/index.vue')['default']
    TableList: typeof import('./components/TableList/index.vue')['default']
    TablePage: typeof import('./components/tablePage/index.vue')['default']
    TagScroll: typeof import('./components/tagScroll/index.vue')['default']
    ThreeD: typeof import('./components/threeD/index.vue')['default']
    TreeItem: typeof import('./components/TreeItem/index.vue')['default']
    TreeList: typeof import('./components/TreeList/index.vue')['default']
    TreeSelect: typeof import('./components/TreeSelect/index.vue')['default']
    VirtuallList: typeof import('./components/virtuallList/index.vue')['default']
    WangEditor: typeof import('./components/wangEditor/index.vue')['default']
  }
}

export { }
